# Generated by Django 3.2.4 on 2021-06-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/restaurants')),
                ('name', models.CharField(max_length=150)),
                ('house', models.CharField(default='', max_length=50)),
                ('street', models.CharField(default='', max_length=50)),
                ('pincode', models.IntegerField(max_length=6)),
                ('online_status', models.BooleanField(default=True)),
                ('active_status', models.BooleanField(default=False)),
                ('from_hrs', models.IntegerField(default=6)),
                ('to_hrs', models.IntegerField(default=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.area')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customer')),
            ],
        ),
    ]
