# Generated by Django 3.2.4 on 2021-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
