# Generated by Django 3.2.4 on 2021-06-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.address'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
