# Generated by Django 3.2.4 on 2021-06-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_order_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.authorization'),
        ),
    ]
