# Generated by Django 3.2.4 on 2021-06-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20210609_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='restaurant',
        ),
    ]
