# Generated by Django 3.2.4 on 2021-06-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20210609_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='address',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.order'),
        ),
    ]
