# Generated by Django 3.2.4 on 2021-06-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20210609_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='restaurant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.restaurant'),
        ),
    ]
