# Generated by Django 3.2.4 on 2021-06-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20210610_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
    ]
