# Generated by Django 3.2.4 on 2021-06-12 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20210612_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.transaction'),
            preserve_default=False,
        ),
    ]
