# Generated by Django 3.2.4 on 2021-06-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_auto_20210612_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.address'),
        ),
    ]
