# Generated by Django 3.2.4 on 2021-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_auto_20210612_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
