# Generated by Django 3.2.6 on 2021-08-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.IntegerField(default=15),
        ),
    ]
