# Generated by Django 3.2.6 on 2021-08-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_order_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='restaurant',
        ),
    ]
