# Generated by Django 3.2.6 on 2021-08-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_remove_rating_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='dish',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='client.dish'),
            preserve_default=False,
        ),
    ]
