from .indexView import IndexView
from .restsView import RestsView
from .restDetailsView import RestDetailsView
from .loginView import LoginView
from .signupView import SignupView
from .orderEssentialsView import OrderEssentialsView
from .logoutView import LogoutView
from .demoView import DemoView
from .restSignupView import RestSignupView
from .ordersView import OrdersView
from .getAreas import GetAreas
from .invoiceGenerator import render_invoice
from .dishDetailsView import DishDetailsView
from .paymentView import PaymentsView
from .dishRatingView import DishRating
